services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/

  bot:
    build:
      context: ./
    restart: always
    volumes:
      - ./src:/app
    command: sh -c "crond & python telegram.py"
